[package]
name = "pebbles-game-io"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
gstd = { version = "1.3.1-pre.3" }
gmeta = { version = "1.3.1-pre.3" }
parity-scale-codec = { version = "3", default-features = false }
scale-info = { version = "2", default-features = false }